class Rx_BackWeaponAttachment_MarksmanRifle_GDI extends Rx_BackWeaponAttachment_MarksmanRifle;

DefaultProperties
{
	Materials[2]=MaterialInstanceConstant'RX_WP_SniperRifle.Materials.MI_Lense_Translucent_GDI'
}
