class Rx_BackWeaponAttachment_MarksmanRifle_Nod extends Rx_BackWeaponAttachment_MarksmanRifle;

DefaultProperties
{
	Materials[0]=MaterialInstanceConstant'RX_WP_SniperRifle.Materials.MI_WP_SniperRifle_Nod'
	Materials[2]=MaterialInstanceConstant'RX_WP_SniperRifle.Materials.MI_DSR50_Lens_Nod'
}
