class S_FamilyInfo_BlackHand_LaserChainGunner extends Rx_FamilyInfo_Nod_LaserChainGunner;

DefaultProperties
{
	CharacterMesh=SkeletalMesh'S_CH_Nod_BHS.Materials.SK_CH_LaserChainGunner'
	InvManagerClass = class'S_InventoryManager_Nod_LaserChainGunner'
}