class S_FamilyInfo_BlackHand_BlackHandSniper extends Rx_FamilyInfo_Nod_BlackHandSniper;

DefaultProperties
{
	CharacterMesh=SkeletalMesh'S_CH_Nod_BHS.Materials.SK_CH_BlackHandSniper'
	InvManagerClass = class'S_InventoryManager_BH_BlackHandSniper'
}