class S_FamilyInfo_BlackHand_RocketSoldier extends Rx_FamilyInfo_Nod_RocketSoldier;

DefaultProperties
{
	CharacterMesh=SkeletalMesh'S_ch_nod_officer.Materials.SK_CH_RocketOfficer_Nod'
	InvManagerClass = class'S_InventoryManager_BH_RocketSoldier'
}